--[[ZAKA HUD - MESSY VERSION]]local a=game:GetService("Players")local b=game:GetService("RunService")local c=game:GetService("UserInputService")local d=game:GetService("TweenService")local e=game:GetService("Lighting")local f=game:GetService("VirtualUser")local g=a.LocalPlayer local h=workspace.CurrentCamera
local S={Aimbot=false,AimbotFOV=135,AimbotSmooth=0.14,AimbotTeamCheck=true,AimbotWallCheck=true,NPCAimbot=false,NPCAimbotFOV=145,ESP=false,ESPBox=true,ESPName=true,ESPHealth=true,ESPDistance=true,ESPTracer=false,ESPMaxDist=2600,ESPTeamCheck=false,NPCESP=false,Speed=false,SpeedValue=30,Fly=false,FlySpeed=80,Noclip=false,InfiniteJump=false,ClickTP=false,GodMode=false,InfiniteAmmo=false,VehicleSpeed=false,VehicleSpeedValue=180,Fullbright=false,FireAura=false,IceAura=false,ElectricAura=false,RainbowBody=false,AntiAFK=true}
local Flying=false local BV,BG local NoclipC,SpeedC,GodC,RainC,VehC local CapeM,CapeC local ESPO={}local MagC={}
g.Idled:Connect(function()if S.AntiAFK then f:CaptureController()f:ClickButton2(Vector2.new())end end)
local function CC(ch)if CapeM then CapeM:Destroy()end if CapeC then CapeC:Disconnect()end local ts=ch:FindFirstChild("UpperTorso")or ch:FindFirstChild("Torso")if not ts then return end CapeM=Instance.new("Model")CapeM.Name="ZakaCape"local cp=Instance.new("Part")cp.Size=Vector3.new(2.3,3.5,0.15)cp.Color=Color3.fromRGB(175,15,15)cp.Material=Enum.Material.Fabric cp.CanCollide=false cp.Massless=true cp.Parent=CapeM local bd=Instance.new("Part")bd.Size=Vector3.new(2.5,3.7,0.08)bd.Color=Color3.fromRGB(255,205,40)bd.Material=Enum.Material.Neon bd.Transparency=0.28 bd.CanCollide=false bd.Massless=true bd.Parent=CapeM local bw=Instance.new("Weld")bw.Part0=cp bw.Part1=bd bw.C0=CFrame.new(0,0,0.03)bw.Parent=bd local w=Instance.new("Weld")w.Part0=ts w.Part1=cp w.C0=CFrame.new(0,0.28,1.12)*CFrame.Angles(math.rad(7),0,0)w.Parent=cp CapeM.Parent=ch local base=w.C0 CapeC=b.RenderStepped:Connect(function()if not cp or not cp.Parent then return end if Flying then w.C0=base*CFrame.Angles(math.rad(-17),math.sin(tick()*9)*0.17,0)else w.C0=base*CFrame.Angles(math.rad(4),math.sin(tick()*2.1)*0.08,0)end end)end
local function RC()if CapeC then CapeC:Disconnect()CapeC=nil end if CapeM then CapeM:Destroy()CapeM=nil end end
local function SF()if Flying then return end local ch=g.Character if not ch or not ch:FindFirstChild("HumanoidRootPart")then return end Flying=true local rt=ch.HumanoidRootPart local hm=ch:FindFirstChildOfClass("Humanoid")if hm then hm.PlatformStand=true end BV=Instance.new("BodyVelocity")BV.MaxForce=Vector3.new(9e9,9e9,9e9)BV.Parent=rt BG=Instance.new("BodyGyro")BG.MaxTorque=Vector3.new(9e9,9e9,9e9)BG.P=4e4 BG.Parent=rt CC(ch)
b:BindToRenderStep("ZakaFly",Enum.RenderPriority.Camera.Value,function()if not Flying or not rt.Parent then return end local cam=h.CFrame local dir=Vector3.zero if c:IsKeyDown(Enum.KeyCode.W)then dir=dir+cam.LookVector end if c:IsKeyDown(Enum.KeyCode.S)then dir=dir-cam.LookVector end if c:IsKeyDown(Enum.KeyCode.A)then dir=dir-cam.RightVector end if c:IsKeyDown(Enum.KeyCode.D)then dir=dir+cam.RightVector end if c:IsKeyDown(Enum.KeyCode.Space)then dir=dir+Vector3.new(0,1,0)end if c:IsKeyDown(Enum.KeyCode.LeftControl)then dir=dir-Vector3.new(0,1,0)end BV.Velocity=dir.Magnitude>0 and dir.Unit*S.FlySpeed or Vector3.zero BG.CFrame=CFrame.new(rt.Position,rt.Position+cam.LookVector)end)end
local function STF()Flying=false pcall(function()b:UnbindFromRenderStep("ZakaFly")end)if BV then BV:Destroy()end if BG then BG:Destroy()end local hm=g.Character and g.Character:FindFirstChildOfClass("Humanoid")if hm then hm.PlatformStand=false end RC()end
local function SS(v)if SpeedC then SpeedC:Disconnect()end if v then SpeedC=b.Heartbeat:Connect(function()local hm=g.Character and g.Character:FindFirstChildOfClass("Humanoid")if hm then hm.WalkSpeed=S.SpeedValue end end)else local hm=g.Character and g.Character:FindFirstChildOfClass("Humanoid")if hm then hm.WalkSpeed=16 end end end
local function SN(v)if NoclipC then NoclipC:Disconnect()end if v then NoclipC=b.Stepped:Connect(function()local ch=g.Character if ch then for _,p in ipairs(ch:GetDescendants())do if p:IsA("BasePart")then p.CanCollide=false end end end end)end end
c.JumpRequest:Connect(function()if S.InfiniteJump then local hm=g.Character and g.Character:FindFirstChildOfClass("Humanoid")if hm then hm:ChangeState(Enum.HumanoidStateType.Jumping)end end end)
c.TouchTap:Connect(function(pos,gpe)if S.ClickTP and not gpe and pos[1]then local ray=h:ViewportPointToRay(pos[1].X,pos[1].Y)local hit,p=workspace:FindPartOnRayWithIgnoreList(Ray.new(ray.Origin,ray.Direction*2000),{g.Character})if hit and g.Character and g.Character:FindFirstChild("HumanoidRootPart")then g.Character.HumanoidRootPart.CFrame=CFrame.new(p+Vector3.new(0,4,0))end end end)
local function SG(v)if GodC then GodC:Disconnect()end if v then GodC=b.Heartbeat:Connect(function()local hm=g.Character and g.Character:FindFirstChildOfClass("Humanoid")if hm then hm.MaxHealth=math.huge hm.Health=math.huge end end)end end
local function SIA(st)S.InfiniteAmmo=st if st then task.spawn(function()while S.InfiniteAmmo do local ch=g.Character if ch then for _,t in ipairs(ch:GetChildren())do if t:IsA("Tool")then pcall(function()if t:FindFirstChild("Ammo")then t.Ammo.Value=999 end if t:FindFirstChild("Clip")then t.Clip.Value=999 end if t:FindFirstChild("CurrentAmmo")then t.CurrentAmmo.Value=999 end end)end end end task.wait(0.4)end end)end end
local function SVS(st)S.VehicleSpeed=st if VehC then VehC:Disconnect()end if st then VehC=b.Heartbeat:Connect(function()local hm=g.Character and g.Character:FindFirstChildOfClass("Humanoid")if hm and hm.SeatPart then local veh=hm.SeatPart.Parent if veh then pcall(function()local seat=veh:FindFirstChildWhichIsA("VehicleSeat")or veh:FindFirstChild("VehicleSeat")if seat then seat.MaxSpeed=S.VehicleSpeedValue end end)end end end)end end
local function SFBF(v)if v then e.Brightness=2.5 e.ClockTime=14 e.FogEnd=1e5 e.GlobalShadows=false else e.Brightness=1 e.FogEnd=1000 e.GlobalShadows=true end end
local function SRB(v)if RainC then RainC:Disconnect()end if v then RainC=b.RenderStepped:Connect(function()local ch=g.Character if not ch then return end local col=Color3.fromHSV(tick()%5/5,1,1)for _,p in ipairs(ch:GetDescendants())do if p:IsA("BasePart")and p.Name\~="HumanoidRootPart"then p.Color=col end end end)end end
local FOV=Drawing.new("Circle")FOV.Thickness=1.5 FOV.NumSides=64 FOV.Filled=false FOV.Color=Color3.fromRGB(0,180,255)FOV.Transparency=0.7 FOV.Visible=false
local function GCP()local cl,sh=nil,S.AimbotFOV local mp=c:GetMouseLocation()for _,pl in ipairs(a:GetPlayers())do if pl\~=g and pl.Character then local hm=pl.Character:FindFirstChildOfClass("Humanoid")local hd=pl.Character:FindFirstChild("Head")if hm and hm.Health>0 and hd then if S.AimbotTeamCheck and pl.Team==g.Team then continue end local sp,on=h:WorldToViewportPoint(hd.Position)if on then if S.AimbotWallCheck then local ry=Ray.new(h.CFrame.Position,(hd.Position-h.CFrame.Position).Unit*3000)local ht=workspace:FindPartOnRayWithIgnoreList(ry,{g.Character,h})if ht and not ht:IsDescendantOf(pl.Character)then continue end end local ds=(Vector2.new(sp.X,sp.Y)-mp).Magnitude if ds<sh then sh=ds cl=hd end end end end end return cl end
local function GCN()local cl,sh=nil,S.NPCAimbotFOV local mp=c:GetMouseLocation()for _,ob in ipairs(workspace:GetDescendants())do if ob:IsA("Model")and ob:FindFirstChildOfClass("Humanoid")and ob:FindFirstChild("Head")then if a:GetPlayerFromCharacter(ob)then continue end local hm=ob:FindFirstChildOfClass("Humanoid")local hd=ob.Head if hm.Health<=0 then continue end local sp,on=h:WorldToViewportPoint(hd.Position)if on then local ds=(Vector2.new(sp.X,sp.Y)-mp).Magnitude if ds<sh then sh=ds cl=hd end end end end return cl end
b.RenderStepped:Connect(function()FOV.Position=c:GetMouseLocation()FOV.Radius=S.Aimbot and S.AimbotFOV or S.NPCAimbotFOV FOV.Visible=S.Aimbot or S.NPCAimbot if S.Aimbot and c:IsMouseButtonPressed(Enum.UserInputType.MouseButton2)then local t=GCP()if t then h.CFrame=h.CFrame:Lerp(CFrame.new(h.CFrame.Position,t.Position),S.AimbotSmooth)end end if S.NPCAimbot and c:IsMouseButtonPressed(Enum.UserInputType.MouseButton2)then local t=GCN()if t then h.CFrame=h.CFrame:Lerp(CFrame.new(h.CFrame.Position,t.Position),0.14)end end end)
local function CE(pl)if ESPO[pl]then return end local t={Box=Drawing.new("Square"),Name=Drawing.new("Text"),Health=Drawing.new("Text"),Distance=Drawing.new("Text"),Tracer=Drawing.new("Line")}t.Box.Thickness=1.2 t.Box.Filled=false t.Box.Color=Color3.fromRGB(0,200,255)t.Name.Size=14 t.Name.Center=true t.Name.Outline=true t.Name.Color=Color3.fromRGB(255,255,255)t.Health.Size=12 t.Health.Center=true t.Health.Outline=true t.Distance.Size=12 t.Distance.Center=true t.Distance.Outline=true t.Distance.Color=Color3.fromRGB(200,200,200)t.Tracer.Thickness=1.2 t.Tracer.Color=Color3.fromRGB(0,180,255)ESPO[pl]=t end
a.PlayerRemoving:Connect(function(pl)if ESPO[pl]then for _,d in pairs(ESPO[pl])do pcall(function()d:Remove()end)end ESPO[pl]=nil end end)
b.RenderStepped:Connect(function()if not S.ESP then for _,t in pairs(ESPO)do for _,d in pairs(t)do d.Visible=false end end return end for _,pl in ipairs(a:GetPlayers())do if pl==g then continue end if S.ESPTeamCheck and pl.Team==g.Team then if ESPO[pl]then for _,d in pairs(ESPO[pl])do d.Visible=false end end continue end CE(pl)local t=ESPO[pl]local ch=pl.Character if not ch or not ch:FindFirstChild("HumanoidRootPart")or not ch:FindFirstChildOfClass("Humanoid")or ch.Humanoid.Health<=0 then for _,d in pairs(t)do d.Visible=false end continue end local rt=ch.HumanoidRootPart local hm=ch.Humanoid local pos,on=h:WorldToViewportPoint(rt.Position)local ds=(rt.Position-h.CFrame.Position).Magnitude if not on or ds>S.ESPMaxDist then for _,d in pairs(t)do d.Visible=false end continue end local sc=math.clamp(1000/pos.Z,0.3,4)local sz=Vector2.new(34*sc,52*sc)t.Box.Size=sz t.Box.Position=Vector2.new(pos.X-sz.X/2,pos.Y-sz.Y/2)t.Box.Visible=S.ESPBox t.Name.Text=pl.Name t.Name.Position=Vector2.new(pos.X,pos.Y-sz.Y/2-15)t.Name.Visible=S.ESPName t.Health.Text=math.floor(hm.Health).." HP"t.Health.Position=Vector2.new(pos.X,pos.Y+sz.Y/2+2)t.Health.Color=Color3.fromRGB(255-(hm.Health/hm.MaxHealth)*255,(hm.Health/hm.MaxHealth)*255,0)t.Health.Visible=S.ESPHealth t.Distance.Text=math.floor(ds).."m"t.Distance.Position=Vector2.new(pos.X,pos.Y+sz.Y/2+15)t.Distance.Visible=S.ESPDistance t.Tracer.From=Vector2.new(h.ViewportSize.X/2,h.ViewportSize.Y)t.Tracer.To=Vector2.new(pos.X,pos.Y+sz.Y/2)t.Tracer.Visible=S.ESPTracer end end)
local function CM(n)if MagC[n]then MagC[n]:Disconnect()MagC[n]=nil end local ch=g.Character if ch and ch:FindFirstChild("ZakaMagic")then local o=ch.ZakaMagic:FindFirstChild(n)if o then o:Destroy()end end end
local function GMF()local ch=g.Character if not ch then return end local f=ch:FindFirstChild("ZakaMagic")if not f then f=Instance.new("Folder")f.Name="ZakaMagic"f.Parent=ch end return f end
local function SFA(v)CM("FireAura")if not v then return end local ch=g.Character if not ch or not ch:FindFirstChild("HumanoidRootPart")then return end local fd=GMF()local pt=Instance.new("Part")pt.Name="FireAura"pt.Size=Vector3.new(1,1,1)pt.Transparency=1 pt.CanCollide=false pt.Anchored=true pt.Parent=fd local fr=Instance.new("Fire")fr.Size=7 fr.Heat=11 fr.Color=Color3.fromRGB(255,110,20)fr.SecondaryColor=Color3.fromRGB(255,40,0)fr.Parent=pt MagC["FireAura"]=b.RenderStepped:Connect(function()if ch and ch:FindFirstChild("HumanoidRootPart")then pt.CFrame=ch.HumanoidRootPart.CFrame end end)end
local function SIAU(v)CM("IceAura")if not v then return end local ch=g.Character if not ch or not ch:FindFirstChild("HumanoidRootPart")then return end local fd=GMF()local pt=Instance.new("Part")pt.Name="IceAura"pt.Size=Vector3.new(5.5,0.25,5.5)pt.Color=Color3.fromRGB(140,220,255)pt.Material=Enum.Material.Ice pt.Transparency=0.35 pt.CanCollide=false pt.Anchored=true pt.Parent=fd MagC["IceAura"]=b.RenderStepped:Connect(function()if ch and ch:FindFirstChild("HumanoidRootPart")then pt.CFrame=ch.HumanoidRootPart.CFrame*CFrame.new(0,-2.7,0)*CFrame.Angles(0,tick()*1.4,0)end end)end
local function SEA(v)CM("ElectricAura")if not v then return end local ch=g.Character if not ch or not ch:FindFirstChild("HumanoidRootPart")then return end local fd=GMF()local pt=Instance.new("Part")pt.Name="ElectricAura"pt.Size=Vector3.new(1,1,1)pt.Transparency=1 pt.CanCollide=false pt.Anchored=true pt.Parent=fd local pe=Instance.new("ParticleEmitter")pe.Texture="rbxassetid://243664672"pe.Color=ColorSequence.new(Color3.fromRGB(80,160,255),Color3.fromRGB(200,240,255))pe.Size=NumberSequence.new(0.35,0)pe.Lifetime=NumberRange.new(0.15,0.3)pe.Rate=55 pe.Speed=NumberRange.new(5,12)pe.SpreadAngle=Vector2.new(180,180)pe.Parent=pt MagC["ElectricAura"]=b.RenderStepped:Connect(function()if ch and ch:FindFirstChild("HumanoidRootPart")then pt.CFrame=ch.HumanoidRootPart.CFrame end end)end
local SG=Instance.new("ScreenGui")SG.Name="ZakaHeavy"SG.ResetOnSpawn=false SG.ZIndexBehavior=Enum.ZIndexBehavior.Sibling pcall(function()SG.Parent=game:GetService("CoreGui")end)if not SG.Parent then SG.Parent=g:WaitForChild("PlayerGui")end
local OB=Instance.new("TextButton")OB.Size=UDim2.new(0,54,0,54)OB.Position=UDim2.new(0,14,0.3,0)OB.BackgroundColor3=Color3.fromRGB(0,140,255)OB.Text="Z"OB.TextColor3=Color3.fromRGB(255,255,255)OB.TextSize=24 OB.Font=Enum.Font.GothamBold OB.Parent=SG Instance.new("UICorner",OB).CornerRadius=UDim.new(1,0)
local DR=Instance.new("TextLabel")DR.Size=UDim2.new(0,70,0,70)DR.Position=UDim2.new(0.5,-35,0.5,-35)DR.BackgroundTransparency=1 DR.Text="🐉"DR.TextSize=20 DR.Parent=OB
task.spawn(function()local ang=0 while DR and DR.Parent do ang=ang+2.5 DR.Rotation=ang task.wait(0.03)end end)
local MN=Instance.new("Frame")MN.Size=UDim2.new(0,360,0,470)MN.Position=UDim2.new(0,80,0.2,0)MN.BackgroundColor3=Color3.fromRGB(13,13,19)MN.BorderSizePixel=0 MN.Visible=true MN.Parent=SG Instance.new("UICorner",MN).CornerRadius=UDim.new(0,13)
local TP=Instance.new("Frame")TP.Size=UDim2.new(1,0,0,44)TP.BackgroundColor3=Color3.fromRGB(18,18,26)TP.BorderSizePixel=0 TP.Parent=MN Instance.new("UICorner",TP).CornerRadius=UDim.new(0,13)
local TL=Instance.new("TextLabel")TL.Size=UDim2.new(1,-50,1,0)TL.Position=UDim2.new(0,14,0,0)TL.BackgroundTransparency=1 TL.Text="Zaka Heavy 🐉"TL.TextColor3=Color3.fromRGB(0,190,255)TL.TextSize=15 TL.Font=Enum.Font.GothamBold TL.TextXAlignment=Enum.TextXAlignment.Left TL.Parent=TP
local CB=Instance.new("TextButton")CB.Size=UDim2.new(0,30,0,30)CB.Position=UDim2.new(1,-38,0.5,-15)CB.BackgroundColor3=Color3.fromRGB(40,40,52)CB.Text="X"CB.TextColor3=Color3.fromRGB(255,90,90)CB.TextSize=14 CB.Font=Enum.Font.GothamBold CB.Parent=TP Instance.new("UICorner",CB).CornerRadius=UDim.new(0,7)
local drg,ds,sp TP.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then drg=true ds=i.Position sp=MN.Position i.Changed:Connect(function()if i.UserInputState==Enum.UserInputState.End then drg=false end end)end end)
c.InputChanged:Connect(function(i)if drg and(i.UserInputType==Enum.UserInputType.MouseMovement or i.UserInputType==Enum.UserInputType.Touch)then local dl=i.Position-ds MN.Position=UDim2.new(sp.X.Scale,sp.X.Offset+dl.X,sp.Y.Scale,sp.Y.Offset+dl.Y)end end)
local TF=Instance.new("Frame")TF.Size=UDim2.new(1,-16,0,34)TF.Position=UDim2.new(0,8,0,50)TF.BackgroundTransparency=1 TF.Parent=MN
local Tbs={"Player","Combat","ESP","Magic","Misc"}local Cur="Player"local TBt={}local Pgs={}
local function MP(n)local p=Instance.new("ScrollingFrame")p.Size=UDim2.new(1,-16,1,-98)p.Position=UDim2.new(0,8,0,92)p.BackgroundTransparency=1 p.ScrollBarThickness=3 p.CanvasSize=UDim2.new(0,0,0,650)p.Visible=n==Cur p.Parent=MN local l=Instance.new("UIListLayout")l.Padding=UDim.new(0,7)l.Parent=p Pgs[n]=p end
for i,n in ipairs(Tbs)do local bt=Instance.new("TextButton")bt.Size=UDim2.new(1/#Tbs,-4,1,0)bt.Position=UDim2.new((i-1)/#Tbs,2,0,0)bt.BackgroundColor3=n==Cur and Color3.fromRGB(0,160,255)or Color3.fromRGB(30,30,42)bt.Text=n bt.TextColor3=Color3.fromRGB(255,255,255)bt.TextSize=12 bt.Font=Enum.Font.GothamBold bt.Parent=TF Instance.new("UICorner",bt).CornerRadius=UDim.new(0,7)TBt[n]=bt MP(n)bt.MouseButton1Click:Connect(function()Cur=n for nn,bb in pairs(TBt)do bb.BackgroundColor3=nn==n and Color3.fromRGB(0,160,255)or Color3.fromRGB(30,30,42)end for nn,pp in pairs(Pgs)do pp.Visible=nn==n end end)end
local function AT(pg,tx,df,cb)local f=Instance.new("Frame")f.Size=UDim2.new(1,0,0,38)f.BackgroundColor3=Color3.fromRGB(22,22,30)f.BorderSizePixel=0 f.Parent=pg Instance.new("UICorner",f).CornerRadius=UDim.new(0,8)
local l=Instance.new("TextLabel")l.Size=UDim2.new(1,-58,1,0)l.Position=UDim2.new(0,12,0,0)l.BackgroundTransparency=1 l.Text=tx l.TextColor3=Color3.fromRGB(230,230,240)l.TextSize=13 l.Font=Enum.Font.Gotham l.TextXAlignment=Enum.TextXAlignment.Left l.Parent=f
local b=Instance.new("TextButton")b.Size=UDim2.new(0,42,0,22)b.Position=UDim2.new(1,-50,0.5,-11)b.BackgroundColor3=df and Color3.fromRGB(0,170,100)or Color3.fromRGB(50,50,60)b.Text=""b.Parent=f Instance.new("UICorner",b).CornerRadius=UDim.new(1,0)
local c=Instance.new("Frame")c.Size=UDim2.new(0,18,0,18)c.Position=df and UDim2.new(1,-20,0.5,-9)or UDim2.new(0,2,0.5,-9)c.BackgroundColor3=Color3.fromRGB(255,255,255)c.Parent=b Instance.new("UICorner",c).CornerRadius=UDim.new(1,0)
local on=df b.MouseButton1Click:Connect(function()on=not on d:Create(b,TweenInfo.new(0.18),{BackgroundColor3=on and Color3.fromRGB(0,170,100)or Color3.fromRGB(50,50,60)}):Play()d:Create(c,TweenInfo.new(0.18),{Position=on and UDim2.new(1,-20,0.5,-9)or UDim2.new(0,2,0.5,-9)}):Play()cb(on)end)end
AT(Pgs["Player"],"Superman Fly + Cape",false,function(v)S.Fly=v if v then SF()else STF()end end)
AT(Pgs["Player"],"Speed Hack",false,function(v)S.Speed=v SS(v)end)
AT(Pgs["Player"],"Noclip",false,function(v)S.Noclip=v SN(v)end)
AT(Pgs["Player"],"Infinite Jump",false,function(v)S.InfiniteJump=v end)
AT(Pgs["Player"],"Click TP",false,function(v)S.ClickTP=v end)
AT(Pgs["Player"],"God Mode",false,function(v)S.GodMode=v SG(v)end)
AT(Pgs["Player"],"Infinite Ammo",false,function(v)SIA(v)end)
AT(Pgs["Player"],"Vehicle Speed",false,function(v)SVS(v)end)
AT(Pgs["Combat"],"Aimbot Player",false,function(v)S.Aimbot=v end)
AT(Pgs["Combat"],"NPC Aimbot",false,function(v)S.NPCAimbot=v end)
AT(Pgs["Combat"],"Team Check",true,function(v)S.AimbotTeamCheck=v end)
AT(Pgs["Combat"],"Wall Check",true,function(v)S.AimbotWallCheck=v end)
AT(Pgs["ESP"],"ESP Player",false,function(v)S.ESP=v end)
AT(Pgs["ESP"],"ESP Box",true,function(v)S.ESPBox=v end)
AT(Pgs["ESP"],"ESP Name",true,function(v)S.ESPName=v end)
AT(Pgs["ESP"],"ESP Health",true,function(v)S.ESPHealth=v end)
AT(Pgs["ESP"],"ESP Distance",true,function(v)S.ESPDistance=v end)
AT(Pgs["ESP"],"ESP Tracer",false,function(v)S.ESPTracer=v end)
AT(Pgs["ESP"],"NPC ESP",false,function(v)S.NPCESP=v end)
AT(Pgs["Magic"],"Fire Aura",false,function(v)S.FireAura=v SFA(v)end)
AT(Pgs["Magic"],"Ice Aura",false,function(v)S.IceAura=v SIAU(v)end)
AT(Pgs["Magic"],"Electric Aura",false,function(v)S.ElectricAura=v SEA(v)end)
AT(Pgs["Magic"],"Rainbow Body",false,function(v)S.RainbowBody=v SRB(v)end)
AT(Pgs["Misc"],"Fullbright",false,function(v)S.Fullbright=v SFBF(v)end)
AT(Pgs["Misc"],"Anti AFK",true,function(v)S.AntiAFK=v end)
OB.MouseButton1Click:Connect(function()MN.Visible=not MN.Visible end)
CB.MouseButton1Click:Connect(function()MN.Visible=false end)
g.CharacterAdded:Connect(function()task.wait(1.3)if S.Speed then SS(true)end if S.Fly then SF()end if S.Noclip then SN(true)end if S.GodMode then SG(true)end end)
print("Zaka Heavy Loaded")
